applicationID: 'Set in botpress-messenger.config.yml file...'
accessToken: 'Set in botpress-messenger.config.yml file...'
appSecret: 'Set in botpress-messenger.config.yml file...'
verifyToken: 'Set in botpress-messenger.config.yml file...'
hostname: 'Set in botpress-messenger.config.yml file...'
enabled: false
